{% set name = "deply" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/deply-{{ version }}.tar.gz
  sha256: 6141484100362aea162a743bc2574cf2f9d6c8ffae31d73bb36d5ad95e76a1de
  patches:
    - 0001-use-environment-for-version.patch

build:
  entry_points:
    - deply=deply.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  script_env:
    - VERSION={{ version }}

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pyyaml >=5.1

test:
  imports:
    - deply
  commands:
    - pip check
    - deply --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vashkatsi/deply
  summary: A tool to enforce architectural patterns in python projects
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
