schema_version: 1

context:
  name: deply
  version: "1.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/deply-${{ version }}.tar.gz
  sha256: 10cfe76bcae33c2a9f11299ea5e3b244300b18cf603daf49deb9b4b0dcb3bd12

build:
  number: 0
  noarch: python
  script:
    env:
      VERSION: ${{ version }}
    content: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - deply=deply.main:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - pyyaml >=5.1

tests:
  - python:
      imports:
        - deply
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - deply --help

about:
  summary: A tool to enforce architectural patterns in python projects
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/vashkatsi/deply

extra:
  recipe-maintainers:
    - thewchan
